# Generated by Django 5.1 on 2024-08-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='annotated_images/')),
                ('recognition_type', models.CharField(choices=[('vgg16', 'VGG16'), ('faster_rcnn', 'Faster R-CNN'), ('mask_rcnn', 'Mask R-CNN')], max_length=11)),
                ('confidence_threshold', models.FloatField(default=0.5)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
